#167619944 create header reusable component
andela/persephone-ah-frontend pull request #15
Opened 2019-08-02 10:38 UTC by devPinheiro

#### What does this PR do?
- It contains  a header component

#### Description of Task to be completed?
- add Roboto and Poppins font families
- create header component
- add header styles
- write tests

#### How should this be manually tested?
- After cloning the repo, cd into the root folder

- Install all necessary dependencies by running 

  ``npm install``

- Launch the node server with

  ``npm run dev``

- Using a web browser visit the link below:

  ``localhost:8080/``

- To run local tests using Jest
  
  ``npm test``

#### Any background context you want to provide?
- N/A

#### What are the relevant pivotal tracker stories?
- PT Story link - `[#167619944] (https://www.pivotaltracker.com/story/show/167619944)`

2019-08-04 09:41 UTC, fxola approved these changes
LGTM

2019-08-04 20:00 UTC, dharmykoya requested changes
Please, can you leave a screenshot so we can have a feel of what you have done. thank you

2019-08-05 09:12 UTC, devPinheiro commented
> Please, can you leave a screenshot so we can have a feel of what you have done. thank you

Done

2019-08-05 10:53 UTC, dharmykoya approved these changes

2019-08-05 10:58 UTC, merged